# Generated by Django 3.2.8 on 2021-10-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0003_auto_20211023_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='auth.user'),
        ),
    ]
