# Generated by Django 3.2.8 on 2021-10-23 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0005_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='student',
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
