# Generated by Django 3.2.8 on 2021-10-29 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_auto_20211030_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 29, 23, 6, 36, 535766, tzinfo=utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 10, 29, 23, 51, 36, 535766, tzinfo=utc), verbose_name='Час кінця'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2021, 10, 29, 23, 6, 36, 535766, tzinfo=utc), verbose_name='Час початку'),
        ),
    ]
