# Generated by Django 3.2.8 on 2021-10-29 23:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_auto_20211030_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 10, 29, 23, 53, 3, 307112, tzinfo=utc), verbose_name='Час кінця'),
        ),
    ]
