# Generated by Django 3.2.8 on 2021-10-30 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0013_alter_lesson_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('lesson', 'Урок'), ('test', 'Тест')], default='lesson', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 10, 30, 17, 42, 44, 232002, tzinfo=utc), verbose_name='Час кінця'),
        ),
    ]
