# Generated by Django 3.2.8 on 2021-10-31 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_auto_20211031_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 10, 31, 15, 57, 30, 698455, tzinfo=utc), verbose_name='Час кінця'),
        ),
    ]
