# Generated by Django 3.2.8 on 2021-10-31 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_auto_20211031_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 10, 31, 16, 29, 22, 227397, tzinfo=utc), verbose_name='Час кінця'),
        ),
    ]
