# Generated by Django 3.2.8 on 2021-11-01 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_auto_20211031_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.teacher', verbose_name='Вчитель'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 11, 1, 19, 53, 7, 715134, tzinfo=utc), verbose_name='Час кінця'),
        ),
    ]
