# Generated by Django 3.2.8 on 2021-11-01 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0021_alter_lesson_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 11, 1, 19, 8, 39, 276663, tzinfo=utc), verbose_name='Час кінця'),
        ),
    ]
