# Generated by Django 3.2.8 on 2021-11-02 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_pageviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageviews',
            name='last_day_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageviews',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pageviews',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
