# Generated by Django 3.2.8 on 2021-11-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_auto_20211102_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='hide_link',
            field=models.BooleanField(default=False, verbose_name='Приховати посилання до початку уроку?'),
        ),
    ]
